# Generated by Django 4.1.6 on 2023-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron.py',
            name='sana',
        ),
        migrations.AlterField(
            model_name='bron.py',
            name='vaqt',
            field=models.CharField(max_length=19),
        ),
    ]
