# Generated by Django 4.1.6 on 2023-02-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_specials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tadbir',
        ),
    ]
