# Generated by Django 4.1.6 on 2023-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
