# Generated by Django 4.1.6 on 2023-02-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_menyu_categoriya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menyu',
            old_name='categoriya.py',
            new_name='Categoriya',
        ),
    ]
