# Generated by Django 4.1.6 on 2023-02-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_menyu_categoriyaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menyu',
            old_name='Categoriyaa',
            new_name='categoriya.py',
        ),
    ]
